// Pas de "use client" ici, c'est un composant côté serveur
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// Ici, on exporte correctement `metadata`
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <head>
        {/* Ajout du fichier CSS du design system */}
        <link rel="stylesheet" href="/design-system/dsfr.css" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
